name: Terraform
on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: uses cache
        uses: actions/cache@v4
        id: cache-providers
        with:
          path: .terraform/providers
          key: ${{ runner.os }}-terraform-providers-${{ hashFiles('/terraform.lock.hcl') }}
      - name: Install Terraform
        if: steps.cache-providers.outputs.cache-hit != 'true'
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install terraform
      - name: Initialize Terraform
        run: terraform init
      - name: Validate Terraform
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan