name: Terraform
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    container:
      image: node:14
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: uses cache
        uses: actions/cache@v4
        id: cache-providers
        with:
          path: .terraform/providers
          key: ${{ runner.os }}-terraform-providers-${{ hashFiles('/.terraform.lock.hcl') }}
      - name: Install Terraform
        if: steps.cache-providers.outputs.cache-hit != 'true'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Initialize Terraform
        run: terraform init
      - name: Validate Terraform
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply
        run: terraform apply --auto-approve
