name: 2.Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:light
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update -y
          apt-get install -y unzip curl

      - name: Cache Terraform providers
        uses: actions/cache@v2
        id: cache-providers
        with:
          path: .terraform/plugins
          key: terraform-providers-${{ hashFiles('.terraform.lock.hcl') }}

      - name: Install Terraform
        if: steps.cache-providers.outputs.cache-hit != 'true'
        run: |
          terraform --version
          echo "Terraform version not found in cache. Installing Terraform..."
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install terraform=1.1.7

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        id: init
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply --auto-approve